<a href="https://colab.research.google.com/github/kgopi15/myfirstcode/blob/master/My_Text_Generation(LSTM)_using_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import files
uploaded=files.upload()

In [0]:
cd/content

/content


In [0]:
def read_file(filepath):
    with open(filepath) as f:
        str_text=f.read()
    return str_text

In [0]:
# Install the PyDrive wrapper & import libraries.
# This only needs to be done once per notebook.
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# Authenticate and create the PyDrive client.
# This only needs to be done once per notebook.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

# Download a file based on its file ID.
#
# A file ID looks like: laggVyWshwcyP6kEI-y_W3P8D26sz
file_id = 'REPLACE_WITH_YOUR_FILE_ID'
downloaded = drive.CreateFile({'id': file_id})
print('Downloaded content "{}"'.format(downloaded.GetContentString()))

In [0]:
from google.colab import files

with open('example.txt', 'w') as f:
  f.write('some content')

files.download('example.txt')

In [8]:
read_file('moby_dick_four_chapters.txt')

'Call me Ishmael.  Some years ago--never mind how long\nprecisely--having little or no money in my purse, and nothing\nparticular to interest me on shore, I thought I would sail about a\nlittle and see the watery part of the world.  It is a way I have of\ndriving off the spleen and regulating the circulation.  Whenever I\nfind myself growing grim about the mouth; whenever it is a damp,\ndrizzly November in my soul; whenever I find myself involuntarily\npausing before coffin warehouses, and bringing up the rear of every\nfuneral I meet; and especially whenever my hypos get such an upper\nhand of me, that it requires a strong moral principle to prevent me\nfrom deliberately stepping into the street, and methodically knocking\npeople\'s hats off--then, I account it high time to get to sea as soon\nas I can.  This is my substitute for pistol and ball.  With a\nphilosophical flourish Cato throws himself upon his sword; I quietly\ntake to the ship.  There is nothing surprising in this.  If t

In [0]:
import spacy
nlp=spacy.load('en',disable=['parser', 'tagger','ner'])
nlp.max_length=1198623

In [0]:
def separate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']

In [0]:
d = read_file('moby_dick_four_chapters.txt')
tokens = separate_punc(d)

In [12]:
tokens

['call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on',
 'shore',
 'i',
 'thought',
 'i',
 'would',
 'sail',
 'about',
 'a',
 'little',
 'and',
 'see',
 'the',
 'watery',
 'part',
 'of',
 'the',
 'world',
 'it',
 'is',
 'a',
 'way',
 'i',
 'have',
 'of',
 'driving',
 'off',
 'the',
 'spleen',
 'and',
 'regulating',
 'the',
 'circulation',
 'whenever',
 'i',
 'find',
 'myself',
 'growing',
 'grim',
 'about',
 'the',
 'mouth',
 'whenever',
 'it',
 'is',
 'a',
 'damp',
 'drizzly',
 'november',
 'in',
 'my',
 'soul',
 'whenever',
 'i',
 'find',
 'myself',
 'involuntarily',
 'pausing',
 'before',
 'coffin',
 'warehouses',
 'and',
 'bringing',
 'up',
 'the',
 'rear',
 'of',
 'every',
 'funeral',
 'i',
 'meet',
 'and',
 'especially',
 'whenever',
 'my',
 'hypos',
 'get',
 'such',
 'an',
 'upper',
 'hand',
 '

In [13]:
len(tokens)

11394

In [0]:
#To pass 25 words and predict the next word
train_len= 25+1
text_sequences=[]
for i in range(train_len,len(tokens)):
    seq=tokens[i-train_len:i]
    text_sequences.append(seq)

In [0]:
len(text_sequences[0])

26

In [0]:
text_sequences[1]

['me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on',
 'shore']

In [0]:
' '.join(text_sequences[0])
#idea is to pass first 25 words and predict the 26 th word here 'on'

'call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on'

In [0]:
' '.join(text_sequences[1])
#idea is to pass 25 words and can i predict word 'shore'

'me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore'

In [15]:
len(text_sequences)

11368

In [0]:
#Keras Tokenization,, converting these words in unique numbers

In [0]:
from keras.preprocessing.text import Tokenizer

In [0]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(text_sequences)

In [0]:
sequences=tokenizer.texts_to_sequences(text_sequences)

In [19]:
sequences[0] #text sequence[0] is converted to numerical values, each of these number is an id to the particular words

[964,
 14,
 265,
 51,
 263,
 416,
 87,
 222,
 129,
 111,
 962,
 262,
 50,
 43,
 37,
 321,
 7,
 23,
 555,
 3,
 150,
 261,
 6,
 2704,
 14,
 24]

In [0]:
sequences[1]

[14,
 265,
 51,
 263,
 416,
 87,
 222,
 129,
 111,
 962,
 262,
 50,
 43,
 37,
 321,
 7,
 23,
 555,
 3,
 150,
 261,
 6,
 2704,
 14,
 24,
 965]

In [20]:
tokenizer.index_word

{1: 'the',
 2: 'a',
 3: 'and',
 4: 'of',
 5: 'i',
 6: 'to',
 7: 'in',
 8: 'it',
 9: 'that',
 10: 'he',
 11: 'his',
 12: 'was',
 13: 'but',
 14: 'me',
 15: 'with',
 16: 'as',
 17: 'you',
 18: 'this',
 19: 'at',
 20: 'is',
 21: 'all',
 22: 'for',
 23: 'my',
 24: 'on',
 25: 'be',
 26: "'s",
 27: 'not',
 28: 'from',
 29: 'there',
 30: 'one',
 31: 'up',
 32: 'what',
 33: 'him',
 34: 'so',
 35: 'bed',
 36: 'now',
 37: 'no',
 38: 'about',
 39: 'into',
 40: 'by',
 41: 'were',
 42: 'out',
 43: 'or',
 44: 'harpooneer',
 45: 'had',
 46: 'then',
 47: 'have',
 48: 'an',
 49: 'upon',
 50: 'little',
 51: 'some',
 52: 'old',
 53: 'like',
 54: 'if',
 55: 'they',
 56: 'would',
 57: 'do',
 58: 'over',
 59: 'landlord',
 60: 'thought',
 61: 'room',
 62: 'when',
 63: 'could',
 64: 'here',
 65: 'head',
 66: "n't",
 67: 'night',
 68: 'such',
 69: 'which',
 70: 'man',
 71: 'did',
 72: 'sea',
 73: 'though',
 74: 'time',
 75: 'other',
 76: 'very',
 77: 'go',
 78: 'these',
 79: 'more',
 80: 'first',
 81: 'sort',


In [0]:
for i in sequences[0]:
    print(f"{i} : {tokenizer.index_word[i]}")

964 : call
14 : me
265 : ishmael
51 : some
263 : years
416 : ago
87 : never
222 : mind
129 : how
111 : long
962 : precisely
262 : having
50 : little
43 : or
37 : no
321 : money
7 : in
23 : my
555 : purse
3 : and
150 : nothing
261 : particular
6 : to
2704 : interest
14 : me
24 : on


In [21]:
tokenizer.word_counts #gives how many times a word occur

OrderedDict([('call', 27),
             ('me', 2471),
             ('ishmael', 133),
             ('some', 758),
             ('years', 135),
             ('ago', 84),
             ('never', 449),
             ('mind', 164),
             ('how', 321),
             ('long', 374),
             ('precisely', 37),
             ('having', 142),
             ('little', 767),
             ('or', 950),
             ('no', 1029),
             ('money', 120),
             ('in', 5647),
             ('my', 1812),
             ('purse', 71),
             ('and', 9646),
             ('nothing', 281),
             ('particular', 152),
             ('to', 6497),
             ('interest', 24),
             ('on', 1716),
             ('shore', 26),
             ('i', 7176),
             ('thought', 676),
             ('would', 702),
             ('sail', 104),
             ('about', 1014),
             ('a', 10377),
             ('see', 442),
             ('the', 15566),
             ('watery', 26),
  

In [22]:
len(tokenizer.word_counts) # gives the total number of unique words

2709

In [0]:
vocabulary_size=len(tokenizer.word_counts)

In [24]:
vocabulary_size

2709

In [0]:
#converting sequence to matrix
import numpy as np
sequences= np.array(sequences)

In [26]:
sequences

array([[ 964,   14,  265, ..., 2704,   14,   24],
       [  14,  265,   51, ...,   14,   24,  965],
       [ 265,   51,  263, ...,   24,  965,    5],
       ...,
       [ 960,   12,  168, ...,  264,   53,    2],
       [  12,  168, 2703, ...,   53,    2, 2709],
       [ 168, 2703,    3, ...,    2, 2709,   26]])

In [0]:
from keras.utils import to_categorical

In [0]:
X=sequences[:,:-1] #last column of sequences will be excluded

In [0]:
X

array([[ 964,   14,  265, ...,    6, 2704,   14],
       [  14,  265,   51, ..., 2704,   14,   24],
       [ 265,   51,  263, ...,   14,   24,  965],
       ...,
       [ 960,   12,  168, ...,   11,  264,   53],
       [  12,  168, 2703, ...,  264,   53,    2],
       [ 168, 2703,    3, ...,   53,    2, 2709]])

In [29]:
y=sequences[:,-1]
y

array([  24,  965,    5, ...,    2, 2709,   26])

In [30]:
y.shape

(11368,)

In [0]:
y=to_categorical(y,num_classes=vocabulary_size+1)

In [32]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [33]:
y.shape

(11368, 2710)

In [34]:
X.shape[1]# gives the number of columns of X

25

In [0]:
seq_len=X.shape[1]

In [0]:
#Create a Lstm Model
import keras
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding

In [0]:
def create_model(vocabulary_size, seq_len):
    model = Sequential()
    model.add(Embedding(vocabulary_size, 25, input_length=seq_len))
    model.add(LSTM(150, return_sequences=True))
    model.add(LSTM(150))
    model.add(Dense(150, activation='relu'))

    model.add(Dense(vocabulary_size, activation='softmax'))
    
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
   
    model.summary()
    
    return model

In [38]:
# define model
model = create_model(vocabulary_size+1, seq_len)

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 25, 25)            67750     
_________________________________________________________________
lstm_1 (LSTM)                (None, 25, 150)           105600    
_________________________________________________________________
lstm_2 (LSTM)                (None, 150)               180600    
_________________________________________________________________
dense_1 (Dense)              (None, 150)               22650     
_________________________________________________________________
dense_2 (Dense)              (None, 2710)              409210    
Total params: 785,810
Trainable params: 785,810
Non-trainable params: 0
_________________________________________________________________


In [0]:
from pickle import dump,load

In [40]:
# fit model
model.fit(X, y, batch_size=128, epochs=300,verbose=1)

Instructions for updating:
Use tf.cast instead.
Epoch 1/300
11368/11368 [==============================] - 12s 1ms/step - loss: 6.8640 - acc: 0.0450
Epoch 2/300
11368/11368 [==============================] - 8s 665us/step - loss: 6.3879 - acc: 0.0527
Epoch 3/300
11368/11368 [==============================] - 8s 701us/step - loss: 6.3506 - acc: 0.0527
Epoch 4/300
11368/11368 [==============================] - 8s 732us/step - loss: 6.2334 - acc: 0.0527
Epoch 5/300
11368/11368 [==============================] - 8s 729us/step - loss: 6.0891 - acc: 0.0535
Epoch 6/300
11368/11368 [==============================] - 8s 681us/step - loss: 5.9569 - acc: 0.0588
Epoch 7/300
11368/11368 [==============================] - 7s 655us/step - loss: 5.8537 - acc: 0.0663
Epoch 8/300
11368/11368 [==============================] - 7s 656us/step - loss: 5.7738 - acc: 0.0669
Epoch 9/300
11368/11368 [==============================] - 8s 665us/step - loss: 5.6981 - acc: 0.0700
Epoch 10/300
11368/11368 [=========

In [0]:
# save the model to file
model.save('epochBIG.h5')
# save the tokenizer
dump(tokenizer, open('epochBIG', 'wb'))

In [0]:
from random import randint
from pickle import load
from keras.models import load_model
from keras.preprocessing.sequence import pad_sequences

In [0]:
def generate_text(model, tokenizer, seq_len, seed_text, num_gen_words):
    '''
    INPUTS:
    model : model that was trained on text data
    tokenizer : tokenizer that was fit on text data
    seq_len : length of training sequence
    seed_text : raw string text to serve as the seed
    num_gen_words : number of words to be generated by model
    '''
    
    # Final Output
    output_text = []
    
    # Intial Seed Sequence
    input_text = seed_text
    
    # Create num_gen_words
    for i in range(num_gen_words):
        
        # Take the input text string and encode it to a sequence
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        
        # Pad sequences to our trained rate (50 words in the video)
        pad_encoded = pad_sequences([encoded_text], maxlen=seq_len, truncating='pre')
        
        # Predict Class Probabilities for each word
        pred_word_ind = model.predict_classes(pad_encoded, verbose=0)[0]
        
        # Grab word
        pred_word = tokenizer.index_word[pred_word_ind] 
        
        # Update the sequence of input text (shifting one over with the new word)
        input_text += ' ' + pred_word
        
        output_text.append(pred_word)
        
    # Make it look like a sentence.
    return ' '.join(output_text)

In [45]:
text_sequences[0]

['call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on']

In [0]:
from keras.models import load_model

In [0]:
model=keras.models.load_model('epochBIG.h5')

In [0]:
import random
random.seed(101)
random_pick=random.randint(0,len(text_sequences))

In [0]:
random_seed_text=text_sequences[random_pick]

In [51]:
random_seed_text

['and',
 'throwing',
 'the',
 'clothes',
 'to',
 'one',
 'side',
 'he',
 'really',
 'did',
 'this',
 'in',
 'not',
 'only',
 'a',
 'civil',
 'but',
 'a',
 'really',
 'kind',
 'and',
 'charitable',
 'way',
 'i',
 'stood',
 'looking']

In [0]:
seed_text=' '.join(random_seed_text)

In [53]:
seed_text

'and throwing the clothes to one side he really did this in not only a civil but a really kind and charitable way i stood looking'

In [54]:
generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=25)

"at him a moment for all his tattooings he was on the whole a clean comely looking cannibal what 's all this fuss i have"